### ISSUE TITLE
Breaks cannot be created within flights and do not upload to the database

### ISSUE THREAD

**Issue by LJWu** [LJWu/FCFSleepTracker#4]
Sometimes a user can create a break, sometimes cannot.

Breaks are not uploading to the mySQL database.

Error message at submit my data: Failed to insert break.

After this error, when a user enters a break then deletes the break, then tries to enter a new break they are unable to click on the break start and Break end time boxes (sometimes).

**Comment by OsimonB** [comment]
I believe this error is fixed, if problems persist, I will reopen this.
